### ISSUE TITLE
Anti-captcha config required even if not doing any captcha processing

### ISSUE THREAD

**Issue by eharris** [luk6xff/Packt-Publishing-Free-Learning#154]
I just tried upgrading to the latest version (1.2.2) and it now refuses to run:

```
> packt-cli -c configFile.cfg -da
[ERROR] - Exception occurred No option 'key' in section: 'ANTICAPTCHA_DATA'
```

I have no interest in using anti-captcha, and do not intend to setup an account, I just want to download the books already on my account.  Yet I'm unable to even though I'm not doing any processing that involves a captcha?

Also, it should be noted that the example config given in the README.md does not supply this section, so the example given will not work either.

**Comment by mjenczmyk** [comment]
Could you see if #160 resolves your problem? Just install script with pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@downloader and see if it works for you.

**Comment by mjenczmyk** [comment]
Resolved by #160.

**Comment by luk6xff** [comment]
Big thanks to @mjenczmyk  for great support and keeping an eye on the repo!

**Comment by eharris** [comment]
This is still not resolved.  The script still fails to run if either the `ANTICAPTCHA_DATA` section is missing:
```
[ERROR] - Exception occurred No section: 'ANTICAPTCHA_DATA'
```

or if the `key` configuration isn't given.
```
[ERROR] - Exception occurred No option 'key' in section: 'ANTICAPTCHA_DATA'
```

Tested with current release 1.4.3.

**Comment by mjenczmyk** [comment]
It has been resolved, but they started to require ReCaptcha solution also for login request.
